import { FullBodyProgram, MuscleGroup, UserProfile, WorkoutItem } from '../types';
import { generateFullBodyWorkout as generateV2 } from './workoutEngineV2';

const MUSCLES: MuscleGroup[] = ['peitoral','costas','ombros','biceps','triceps','quadriceps','posteriores','gluteos','panturrilhas','core'];
const EMPTY = (): Record<MuscleGroup, number> => Object.fromEntries(MUSCLES.map((m)=>[m,0])) as Record<MuscleGroup,number>;
const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v));
function sessionBudget(minutes:number){if(minutes<=30)return 7;if(minutes<=45)return 10;if(minutes<=60)return 14;if(minutes<=75)return 18;return 22;}
function indirectFactor(item:WorkoutItem, secondary:MuscleGroup){if(!item.exercise.musculosSecundarios.includes(secondary)||item.exercise.categoria==='isolation')return 0;return secondary==='biceps'||secondary==='triceps'?0.5:0.35;}
function parseRepMidpoint(range:string){const m=range.match(/(\d+)\s*-\s*(\d+)/);return m?(Number(m[1])+Number(m[2]))/2:10;}
function estimateMinutes(items:WorkoutItem[]){const transition=Math.max(0,items.length-1)*60;const work=items.reduce((s,i)=>s+i.targetSets*clamp(parseRepMidpoint(i.targetReps)*3.5,20,60),0);const rest=items.reduce((s,i)=>s+Math.max(0,i.targetSets-1)*i.targetRestSec,0);return Math.ceil((transition+work+rest+(items.length?300:0))/60);}
function rebalanceDay(dayItems:WorkoutItem[],target:Record<MuscleGroup,number>,priorities:MuscleGroup[],budget:number){const freq=EMPTY();dayItems.forEach(i=>freq[i.exercise.grupoMuscular]++);const items=dayItems.map(i=>{let sets=Math.round((target[i.exercise.grupoMuscular]||10)/Math.max(1,freq[i.exercise.grupoMuscular]));if(priorities.includes(i.exercise.grupoMuscular))sets++;return {...i,targetSets:clamp(sets,2,5)};});let total=items.reduce((s,i)=>s+i.targetSets,0);const order=[...items].sort((a,b)=>{const ap=priorities.includes(a.exercise.grupoMuscular)?1:0,bp=priorities.includes(b.exercise.grupoMuscular)?1:0;const ai=a.exercise.categoria==='isolation'?0:1,bi=b.exercise.categoria==='isolation'?0:1;return ap-bp||ai-bi||b.exercise.fatigueIndex-a.exercise.fatigueIndex;});for(const item of order){while(total>budget&&item.targetSets>2){item.targetSets--;total--;}}return items;}
function recompute(splitDays:FullBodyProgram['splitDays']){const weekly=EMPTY(),frequency=EMPTY();for(const day of splitDays){for(const item of day.items){const p=item.exercise.grupoMuscular;weekly[p]+=item.targetSets;frequency[p]++;for(const secondary of item.exercise.musculosSecundarios){const factor=indirectFactor(item,secondary);weekly[secondary]+=Math.round(item.targetSets*factor*10)/10;frequency[secondary]+=factor;}}day.estimatedTimeMin=estimateMinutes(day.items);const weighted=day.items.reduce((s,i)=>s+i.exercise.fatigueIndex*i.targetSets,0);const max=day.items.reduce((s,i)=>s+5*i.targetSets,0);day.systemicFatigueScore=max?Math.round(weighted/max*100):0;}return {weekly,frequency};}
export function generateFullBodyWorkout(rawProfile:UserProfile, recentExerciseIds:Set<string>=new Set()):FullBodyProgram{const base=generateV2(rawProfile,recentExerciseIds);const target=base.targetWeeklyVolumeMap||base.weeklyVolumeMap;const priorities=base.profile.priorities||[];const splitDays=base.splitDays.map(day=>({...day,items:rebalanceDay(day.items,target,priorities,sessionBudget(base.profile.timePerSessionMin))}));const warnings=[...(base.generationWarnings||[])];for(const day of splitDays){const est=estimateMinutes(day.items);if(est>base.profile.timePerSessionMin+10)warnings.push(`Sessão ${day.id} estimada em ${est} min, acima da janela de ${base.profile.timePerSessionMin} min.`);}const {weekly,frequency}=recompute(splitDays);return {...base,splitDays,weeklyVolumeMap:weekly,frequencyMap:frequency,generationWarnings:Array.from(new Set(warnings))};}
